<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="A1877-PF2C5JHR" failures="6" tests="8" name="Tests" time="41.794" errors="0" timestamp="2024-11-06T15:37:56 IST">
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.HomePageTest" name="homePageTest" time="0.123"/>
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignUpTest" name="signUpTest" time="1.119"/>
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignUpTest" name="signUpTest" time="0.792">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Sign Up button should be disabled for invalid credentials. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]
at com.xalts.tst.assignment_xalts_TestCases.SignUpTest.signUpTest(SignUpTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- signUpTest -->
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignUpTest" name="signUpTest" time="0.797">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Sign Up button should be disabled for invalid credentials. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]
at com.xalts.tst.assignment_xalts_TestCases.SignUpTest.signUpTest(SignUpTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- signUpTest -->
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignUpTest" name="signUpTest" time="0.614">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Sign Up button should be disabled for invalid credentials. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]
at com.xalts.tst.assignment_xalts_TestCases.SignUpTest.signUpTest(SignUpTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- signUpTest -->
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignInTest" name="signInTest" time="2.224">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: &amp;apos;4.25.0&amp;apos;, revision: &amp;apos;8a8aea2337&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.10&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()=&amp;apos;Sign Out&amp;apos;], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282
at com.xalts.tst.assignment_xalts_TestCases.SignInTest.signInTest(SignInTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- signInTest -->
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignInTest" name="signInTest" time="0.789">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: &amp;apos;4.25.0&amp;apos;, revision: &amp;apos;8a8aea2337&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.10&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()=&amp;apos;Sign Out&amp;apos;], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282,
	&amp;apos;Sign In&amp;apos; button should be disabled for invalid credentials. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282,
'Sign In' button should be disabled for invalid credentials. expected [false] but found [true]
at com.xalts.tst.assignment_xalts_TestCases.SignInTest.signInTest(SignInTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- signInTest -->
  <testcase classname="com.xalts.tst.assignment_xalts_TestCases.SignOutTest" name="signOutTest" time="1.896">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: &amp;apos;4.25.0&amp;apos;, revision: &amp;apos;8a8aea2337&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.10&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [45d306f9d96499e5c70c26c6b7bd4321, findElement {value=//button[normalize-space()=&amp;apos;Sign Out&amp;apos;], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64120}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64120/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 45d306f9d96499e5c70c26c6b7bd4321">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [45d306f9d96499e5c70c26c6b7bd4321, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64120}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64120/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 45d306f9d96499e5c70c26c6b7bd4321
at com.xalts.tst.assignment_xalts_TestCases.SignOutTest.signOutTest(SignOutTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- signOutTest -->
  <testcase classname="com.xalts.test.assignment_xalts_base.BaseClass" name="@BeforeSuite loadConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite loadConfig -->
  <testcase classname="com.xalts.test.assignment_xalts_base.BaseClass" name="@BeforeSuite loadConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite loadConfig -->
  <testcase classname="com.xalts.test.assignment_xalts_base.BaseClass" name="@BeforeSuite loadConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite loadConfig -->
  <testcase classname="com.xalts.test.assignment_xalts_base.BaseClass" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
  <testcase classname="com.xalts.test.assignment_xalts_base.BaseClass" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
  <testcase classname="com.xalts.test.assignment_xalts_base.BaseClass" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
</testsuite> <!-- Tests -->
